import { defineStore } from "pinia";
import { reactive } from "vue";
export const useEmployees = defineStore("employees", () => {
  const formData = reactive({
    nama: "test",
    blood_type: "A",
    gender: "gk jelas",
    pendidikan: "militer",
    universitas: "itb",
    jurusan: "bandung",
    ipk: "4.5",
    ibu_kandung: "mama",
    status_karyawan: "selamanya",
    nama_pasangan: "",
    tanggungan: "banyak",
    no_ktp: "2155341245",
    nama_ktp: "siapa",
    alamat_ktp: "dmna aja",
    rt_ktp: "010",
    rw_ktp: "020",
    provinsi_ktp: "jawa barat",
    kota_ktp: "cirebon",
    kelurahan_ktp: "kecapi",
    kecamatan_ktp: "harjamukti",
    kode_pos_ktp: "25215",
    alamat_tinggal: "Jl.Iskandar Muda",
    rt: "001",
    rw: "002",
    provinsi: "Jakarta",
    kota: "Jakarta",
    kelurahan: "Dadap",
    kecamatan: "Kosambi",
    kode_pos: "255416",
    tgl_lahir: "1945-08-17",
    tempat_lahir: "Belanda",
    agama: "setan",
    telp: "124141",
    hp: "41542454",
    no_rek_cf: "2522525",
    no_rek_tf: "4521525",
    email: "ajkah@gmail.com",
    npwp: "12521545",
    sumber_loker: "IG",
    ket_loker: "Loker",
    interview: "asaas",
    tgl_keluar: "2024-02-02",
    alasan_keluar: "gaji tinggi",
    cuti: "50",
    photo_loc: "",
    spv_id: "",
    status_mst: "Active",
  });
  return { formData };
});
