const kunjungan = {
  // pinjaman
  cust_code_ref: "",
  tujuan_kredit: "pilih",
  plafond: "",
  tenor: "pilih",
  kategori: "pilih",
  //nasabah
  no_ktp: "",
  nama: "",
  tgl_lahir: "",
  alamat: "",
  rt: "",
  rw: "",
  provinsi: "",
  kota: "",
  kecamatan: "",
  desa: "",
  hp: "",
  nama_ibu_kandung: "",
  dependants: "",
  tin_number: "",
  title: "",
  //pekerjaan
  lama_bekerja: "",
  pendapatan: "",
  pendapatan_pasangan: "",
  pendapatan_lain: "",
  pengeluaran: "",
  ref_pembayaran: "",
  usaha: "",
  sektor: "",
  catatan_survey: "",
  //jaminan
  jaminan: [
    {
      tipe: "",
      merk: "",
      tahun: "",
      warna: "",
      atas_nama: "",
      nilai: "",
      no_polisi: "",
      no_rangka: "",
      no_mesin: "",
      no_bpkp: "",
    },
  ],
};
const attachKunjungan = {
  file_ktp: "",
  file_ktp_pasangan: "",
  file_kk: "",
  jaminan: [
    {
      no_rangka: "",
      no_mesin: "",
      stnk: "",
      depan: "",
      belakang: "",
      kanan: "",
      kiri: "",
    },
  ],
};

const fpk = {
  //pelanggan
  nama: "",
  nama_panggaila: "",
  jenis_kelamin: "",
  tempat_lahir: "",
  tanggal_lahir: "",
  golongan_darah: "",
  status_kawin: "",
  tanggal_kawin: "",
  identitas: "",
  no_identitas: "",
  no_kk: "",
  warganegara: "",
  pekerjaan: "",
  pekerjaan_id: "",
  agama: "",
  pendidikan: "",
  status_rumah: "",
  telepon_rumah: "",
  telepon_selular: "",
  telepon_kantor: "",
  ext1: "",
  ext2: "",
  alamat_identitas: "",
  rt_identitas: "",
  rw_identitas: "",
  provinsi_identitas: "",
  kota_identitas: "",
  kecamatan_identitas: "",
  desa_identitas: "",
  kodepos_identitas: "",
  alamat_tagih: "",
  rt_tagih: "",
  rw_tagih: "",
  provinsi_tagih: "",
  kota_tagih: "",
  kecamatan_tagih: "",
  desa_tagih: "",
  kodepos_tagih: "",
  //order
  nama_ibu_kandung: "",
  kategori: "",
  gelar: "",
  lama_bekerja: "",
  tanggungan: "",
  pendapatan: "",
  pendapatan_pasangan: "",
  pendapatan_lain: "",
  pengeluaran: "",
  tanggal_order: "",
  status_order: "",
  tipe_order: "",
  pelanggan_group: "",
  unit_bisnis: "",
  cust_service: "",
  ref_pelanggan: "",
  surveyor: "",
  catatan_survey: "",
  platform: "",
  prog_marketing: "",
  cara_bayuar: "",
  no_npwp: "",
  alamat_npwp: "",
  rt_npwp: "",
  rw_npwp: "",
  provinsi_npwp: "",
  kota_npwp: "",
  kecamatan_npwp: "",
  desa_npwp: "",
  kodepos_npwp: "",
  kode_barang_taksasi: "",
  id_tipe_taksasi: "",
  tahun_taksasi: "",
  harga_taksasi: "",
  //tambahan
  nama_bi: "",
  email: "",
  info_khusus: "",
  usaha_lain1: "",
  usaha_lain2: "",
  usaha_lain3: "",
  nama_darurat: "",
  alamat_darurat: "",
  rt_darurat: "",
  rw_darurat: "",
  provinsi_darurat: "",
  kota_darurat: "",
  kecamatan_darurat: "",
  desa_darurat: "",
  kodepos_darurat: "",
  telepon_rumah_darurat: "",
  telepon_selular_darurat: "",
  alamat_surat: "",
  rt_surat: "",
  rw_surat: "",
  provinsi_surat: "",
  kota_surat: "",
  kecamatan_surat: "",
  desa_surat: "",
  kodepos_surat: "",
  info_bank: [
    {
      kode_bank: "",
      nama_bank: "",
      currency: "",
      no_rekening: "",
      nama_rekening: "",
      status: "",
    },
  ],
  //extra
  pokok_pembayaran: "",
  tipe_angsuran: "",
  advance_arrear: "",
  jumlah_angsuran: "",
  periode: "",
  angsuran: "",
  total: "",
  cadangan: "",
  biaya_broker: "",
  provisi: "",
  asuransi: "",
  biaya_transfer: "",
  bunga_margin_eff: "",
  bunga_margin_flat: "",
  bunga_margin: "",
  poko_margin: "",
  angsuran_terakhir: "",
  bunga_margin_eff_actual: "",
  bunga_margin_eff_flat: "",
  provisi: "",
  nett_admin: "",
  nilai_diterima: "",
};
